repos:
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        args: [-S, --line-length=100]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        args: [--max-line-length=100, '--ignore=F401, W503']
  - repo: local
    hooks:
      - id: version_increase
        name: version_increase
        description: Increase version in constants.json
        entry: env/bin/python config/increase_version.py
        language: python
        files: ^$
        args: [patch]
        always_run: true
